<script data-cfasync="false"
        src="{{ asset('cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js') }}"></script>
<script src="{{ asset('js/jquery_min.js') }}"></script>
<script src="{{ asset('js/jqu_menu.js') }}"></script>
<script src="{{ asset('js/jqu_slickmenu.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/jquery.countTo.js') }}"></script>
<script src="{{ asset('js/wow.min.js') }}"></script>
<script src="{{ asset('js/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('venobox/js/venobox.min.js') }}"></script>
<script src="{{ asset('js/jquery.easypiechart.min.js') }}"></script>
<script src="{{ asset('js/progress-script.js') }}"></script>
<script src="{{ asset('js/owl.carousel.js') }}"></script>
<script src="{{ asset('js/jquery.inview.min.js') }}"></script>
<script src="{{ asset('js/jquery.mixitup.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/jquery.themepunch.revolution.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/jquery.themepunch.tools.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.addon.snow.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.actions.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.carousel.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.kenburn.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.layeranimation.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.migration.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.navigation.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.parallax.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.slideanims.min.js') }}"></script>
<script src="{{ asset('js/plugin/rs_slider/revolution.extension.video.min.js') }}"></script>
<script src="{{ asset('js/responsive_header.js') }}"></script>
<script src="{{ asset('js/custom.js') }}"></script>
<!--js code-->
